services:
  - type: web
    name: vacancy-tracker-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn backend_vac_tr_main.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "yourdomain.onrender.com,.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: vacancy-tracker-db
          property: connectionString

databases:
  - name: vacancy-tracker-db
    databaseName: vacancy_tracker
    user: vacancy_user
    plan: free
